const hsMedications = [
    "Clindamycin",
    "Resorcinol Cream",
    "Doxycycline",
    "Contraceptives",
    "Spironolactone",
    "Acitretin",
    "Adalimumab",
    "Infliximab",
    "Methotrexate",
    "Cyclosporine",
    "Ibuprofen",
    "Prednisone",
    "Acetaminophen",
    "Tetracycline (doxycycline, minocycline)",
    "Spironolactone",
    "Finasteride",
    "Isotretinoin (Accutane)",
    "Acitretin",
    "Metformin",
    "Dapsone",
    "Cyclosporine",
    "Methotrexate",
    "Prednisone",
    "Triamcinolone acetonide",
    "Infliximab (Remicade)",
    "Etanercept",
    "Tofacitinib"
];

// https://pubmed.ncbi.nlm.nih.gov/33493574/
const comorbidities = [
    "Acne",
    "Dyslipidemia",
    "PD (Pilonidal Disease)",
    "PG (Pyoderma Gangrenosum",
    "Herpes Zoster",
    "Polycystic Ovary Syndrome",
    "Dyslipidemia (High Cholesterol)",
    "Musculoskeletal Disease",
    "Sexual Dysfunction",
    "Down Syndrome",
    "Diabetes",
    "Obesity",
    "Hypertension",
    "Crohn's Disease",
    "Psoriasis",
    "Arthritis",
    "Asthma",
    "Cardiovascular Disease",
    "Cancer",
    "IBD (Inflammatory Bowel Disease)",
    "Lupus",
    "Depression",
    "Epilepsy",
    "GAD (Generalized Anxiety Disorder)",
    "None"
];

const hsBiologics = [
    "Adalimumab (Humira)",
    "Infliximab (Remicade)",
    "Secukinumab (Cosentyx)",
    "Ustekinumab (Stelara)",
    "Etanercept (Enbrel)",
    "Tildrakizumab (Ilumya)",
    "Guselkumab (Tremfya)",
    "Brodalumab (Siliq)"
];